version: '3.8'

services:
  weather-app:
    build:
      context: ./message-listener
      dockerfile: Dockerfile
    container_name: weather-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT:-1883}
    volumes:
      - weather_db_data:/app/data
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s # Gives Spring Boot time to start up before checking

volumes:
  weather_db_data: