# SQLite Datasource
spring:
  datasource:
    url: jdbc:sqlite:/app/data/weather.db

# MQTT Broker Settings (Values injected by Docker Compose from .env)
mqtt:
  broker:
    url: tcp://${MQTT_HOST}:${MQTT_PORT:1883}